[env] ## tells cargo make that we're in the context of a Cargo workspace
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

[tasks.dev]
install_crate="cargo-watch"
cwd = "./crates/jayden_bin"
command = "cargo"
args = ["watch", "-x", "clippy", "-x", "run"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fix]
command = "cargo"
args = ["fix","--allow-dirty"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build" , "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-watch]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "test"]

[tasks.migrate] ## ensure Postgres is running, the container has a bit of warmup time causing migrations to fail
cwd = "./crates/jayden_infrastructure"
command = "sqlx"
args = ["migrate", "run"]
dependencies = ["postgres"]
