version: "3.9"

name: "database"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: jayden.dangvu
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jaydendb
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
      # - jayden_data:/var/lib/postgresql/data

# volumes:
#   jayden_data:
