version: '3.9'

services:
  database_jayden:
    container_name: database_jayden
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jayden
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jayden_blog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
